### PR TITLE
Implement shortcuts and fix storage bug

### LINKED ISSUE #112: Add shortcuts
When there's no input in the command line, using these shortcuts will auto-fill the command word:
- Add ctrl-N shortcut for `create` command
- Add ctrl-G shortcut for `edit` command
- Add ctrl-F shortcut for `find` command
- Add ctrl-U shortcut for `undo` command

Other shortcuts to add:
- Add ctrl-W shortcut to exit program
- Add ctrl-S shortcut that
  - prompts a success message to assure the user that the progress is auto-saved
  - deal with the case where permission of the data file is compromised 
- Add up/down arrow key shortcut to navigate previous commands

- Ensure shortcuts work across different OS

### PR DESCRIPTION
**Pull request by Singa-pirate**
When textbox is focused (active):
- When textbox is empty
  - ctrl-F to auto-fill `find`
  - ctrl-N to auto-fill `create`
  - ctrl-G to auto-fill `edit`
  - ctrl-U to auto-fill `undo`
  - ctrl-R to auto-fill `redo`
- No matter the textbox is empty or not
  - Up arrow to navigate to previous command in history
  - Down arrow to navigate to next command in history

When textbox is unfocused:
  - ctrl-Z to execute an `UndoCommand` immediately
  - ctrl-Y to execute a `RedoCommand` immediately

No matter the textbox is unfocused or not:
  - ctrl-S to execute a `SaveCommand` immediately
  - ctrl-W to exit program

This PR also fixes a bug when the app has no write permission to data file.
The bug caused non-data-changing commands (e.g. `list, help, exit`) 
to be blocked when there's no write permission.
Now, each command class inherits from either `ChangeDataCommand`
or `DoesNotChangeDataCommand`.
Execution of a command will only attempt to store data if the command
is an instance of `ChangeDataCommand`.

Closes #112.

### CODE REVIEW

File: src/main/java/networkbook/logic/LogicManager.java [hunk 1]
```diff
@@ -50,6 +51,10 @@ public CommandResult execute(String commandText) throws CommandException, ParseE
         Command command = networkBookParser.parseCommand(commandText);
         commandResult = command.execute(model);
 
+        if (command instanceof DoesNotChangeDataCommand) {
+            return commandResult;
+        }
```
Comment (nknguyenhc) [inline src/main/java/networkbook/logic/LogicManager.java:55]: Would it be better if changing command is a method that returns a value of a field, i.e.
```java
private boolean isChangingData;

public boolean isChangingData() {
    return this.isChangingData;
}
```
rather than having two separate classes for it? I do not see `ChangeDataCommand` class being in good use, and the current implementation does not force concrete classes to inherit either from `ChangeDataCommand` class or `DoesNotChangeDataCommand` class.

File: src/test/java/networkbook/logic/commands/CommandResultTest.java [hunk 2]
```diff
@@ -12,27 +10,27 @@ public class CommandResultTest {
...
 
-        // different showHelp value -> returns false
-        assertFalse(commandResult.equals(new CommandResult("feedback", true, false)));
+        // different showHelp value -> not equal
+        assertNotEquals(commandResult, new CommandResult("feedback", true, false));
 
-        // different exit value -> returns false
-        assertFalse(commandResult.equals(new CommandResult("feedback", false, true)));
+        // different exit value -> not equal
+        assertNotEquals(commandResult, new CommandResult("feedback", false, true));
```
Comment (nknguyenhc) [inline src/test/java/networkbook/logic/commands/CommandResultTest.java]: I'm unsure if changing the syntax here is good, 
retaining the old syntax highlights that the method `equals` is being tested.

File: src/test/java/networkbook/logic/parser/NetworkBookParserTest.java [hunk 3]
```diff
@@ -139,6 +140,12 @@ public void parseCommand_help() throws Exception {
         assertTrue(parser.parseCommand(HelpCommand.COMMAND_WORD + " 3") instanceof HelpCommand);
     }
 
+    @Test
+    public void parseCommand_save() throws Exception {
+        assertTrue(parser.parseCommand(SaveCommand.COMMAND_WORD) instanceof SaveCommand);
+        assertTrue(parser.parseCommand(SaveCommand.COMMAND_WORD + " 3") instanceof SaveCommand);
+    }
+
```
Comment (nknguyenhc) [inline src/test/java/networkbook/logic/parser/NetworkBookParserTest.java]: Would be better to use `equals` method and override the method in `SaveCommand`
rather than hardcoding the logic of `equals` here.

File: src/main/java/networkbook/ui/CommandBox.java [hunk 4]
```diff
@@ -30,6 +51,43 @@ public CommandBox(CommandExecutor commandExecutor) {
...
+                } else if (SHORTCUT_REDO.match(event)) {
+                    autoFillCommandIfEmpty("redo");
+                    event.consume();
+                } else if (noModifier(event) && event.getCode() == SHORTCUT_UP) {
+                    navigateCommandHistory(true);
+                    event.consume();
+                } else if (noModifier(event) && event.getCode() == SHORTCUT_DOWN) {
+                    navigateCommandHistory(false);
+                    event.consume();
+                }
```
Comment (nknguyenhc) [inline src/main/java/networkbook/ui/CommandBox.java]: Would it be better to use `COMMAND_WORD` field in the respective command,
rather than hardcoding them here?

**Review by nknguyenhc — COMMENTED** [review]
Features work as expected. In terms of class design, I suggest having a method in the `Command` interface rather than having two abstract classes but not forcing concrete classes to inherit from either one of those two abstract classes.

File: src/main/java/networkbook/logic/LogicManager.java (hunk 1 above)
Comment (Singa-pirate) [reply src/main/java/networkbook/logic/LogicManager.java:55]: Okay makes sense, will change to your suggested implementation, with a constructor in `Command` class that must be called from the child classes.

File: src/test/java/networkbook/logic/commands/CommandResultTest.java (hunk 2 above)
Comment (Singa-pirate) [reply src/test/java/networkbook/logic/commands/CommandResultTest.java]: I changed the syntax here because IDE gives a warning 🤣 
Also, it seems that the community standard is to use `assertEquals` in this case, because it displays the difference better, and is null-safe. Reference [here](https://stackoverflow.com/questions/41974209/what-is-the-actual-difference-between-assertequals-vs-asserttrue-in-testng#:~:text=Also%2C%20assertEquals(a%2C%20b,equals(b))%20is%20not.).

File: src/test/java/networkbook/logic/parser/NetworkBookParserTest.java (hunk 3 above)
Comment (Singa-pirate) [reply src/test/java/networkbook/logic/parser/NetworkBookParserTest.java]: Okay will change it

File: src/main/java/networkbook/ui/CommandBox.java (hunk 4 above)
Comment (Singa-pirate) [reply src/main/java/networkbook/ui/CommandBox.java]: Yep okay will replace these hard-coded texts here and also in the test cases.

File: src/test/java/networkbook/logic/commands/CommandResultTest.java (hunk 2 above)
Comment (nknguyenhc) [reply src/test/java/networkbook/logic/commands/CommandResultTest.java]: Yes, in the general case, it is better to use `assertEquals`, but here we are testing the `equals` method, not comparing the two values, so it is better to call the method explicitly.

Comment (Singa-pirate) [reply src/test/java/networkbook/logic/commands/CommandResultTest.java]: Okay I've changed the test cases, please review. Thanks for your suggestion!

**Review by nknguyenhc — APPROVED** [review]
