### PR TITLE
Edit command messages for accuracy and clarity

### LINKED ISSUE #213: [PE-D][Tester B] Wrong example given in an error message
In order to recreate this bug i typed in sort which dhows the error message for missing inputs

But when I try to use the command suggested by the example it doesnt work

This is a simple typo that can be fixed easily but the severity is quite high since people may use this example a lot

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Bryan-Goh/ped#3

### PR DESCRIPTION
**Pull request by xenosf**
* Add some line breaks before "parameter" in usage messages for consistency/readability
* Fix spacing issue in sort usage (fixes #213)
* ~~Add clarification to delete command~~

### CODE REVIEW

File: src/main/java/networkbook/logic/commands/delete/DeletePersonCommand.java [hunk 1]
```diff
@@ -28,7 +28,8 @@ public class DeletePersonCommand extends Command {
             + "Example: " + COMMAND_WORD + " 1\n"
             + "Usage 2: " + COMMAND_WORD + " [LIST INDEX OF CONTACT] [FIELD PREFIX]\n"
             + "Example: " + COMMAND_WORD + " 1 /priority\n"
-            + "If the field can have multiple values, /index must be used to specify index of the entry to delete.\n"
+            + "If the field can have multiple values, /index must be used to specify index of the entry to delete."
+            + "If /index is not specified, defaults to 1.\n"
```
Comment (nknguyenhc) [inline src/main/java/networkbook/logic/commands/delete/DeletePersonCommand.java]: I'm not sure if this change is too much. Maybe can just leave the message as `If the field can have multiple values, /index can be used to specify index of the entry to delete.` I think would be safer this way, and the tester should be referring to the user guide anyway. We can add this as one of the planned enhancements in DG.

**Comment by nknguyenhc** [comment]
I changed the word from `must` to `can`, because technically `/index` does not have to be specified.

**Review by nknguyenhc — APPROVED** [review]
