### PR TITLE
Change target throwing CommandException

### LINKED ISSUE #157: `Model` should not throw `CommandException` for `undo` and `redo`

### PR DESCRIPTION
**Pull request by awhb**
Changed target throwing CommandException from Model to UndoCommand/RedoCommand.

Fixes #157

### CODE REVIEW

File: src/test/java/networkbook/logic/commands/OpenEmailCommandTest.java [hunk 1]
```diff
@@ -34,67 +34,74 @@ public class OpenEmailCommandTest {
...
         }
 
         public boolean isValidLinkIndex(Index personIndex, Index linkIndex) {
-            throw new UnsupportedOperationException();
+            throw new AssertionError("This method should not be called.");
         }
 
         public Link openLink(Index personIndex, Index linkIndex) {
-            throw new UnsupportedOperationException();
+            throw new AssertionError("This method should not be called.");
```
Comment (nknguyenhc) [inline src/test/java/networkbook/logic/commands/OpenEmailCommandTest.java:104]: Please attribute with `//@@author` on top of every method.

File: src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java [hunk 2]
```diff
@@ -34,59 +34,66 @@ public class OpenLinkCommandTest {
...
+            throw new AssertionError("This method should not be called.");
+        }
         public void undoNetworkBook() {
-            throw new UnsupportedOperationException();
+            throw new AssertionError("This method should not be called.");
         }
 
         public void redoNetworkBook() {
-            throw new UnsupportedOperationException();
+            throw new AssertionError("This method should not be called.");
```
Comment (nknguyenhc) [inline src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java:96]: Same thing here.

**Review by nknguyenhc — CHANGES_REQUESTED** [review]
LGTM, just a small authorship attribute request.

**Review by nknguyenhc — APPROVED** [review]
